### ISSUE TITLE
File with the same name

### ISSUE THREAD

**Issue by paulvi** [dbickley/OpenEditors#12]
Some special treatment needed for files with the same name, e.g. `pom.xml`
In Eclipse tabs, project name is added before

![image](https://user-images.githubusercontent.com/1614482/39370045-7a958ff2-4a70-11e8-9e8b-17479fb11c44.png)

**Comment by dbickley** [comment]
Hmm, I will have to think about how to fix this. Maybe a hover over that shows the whole path?

**Comment by achimmihca** [comment]
I would suggest to look at the behavior of IntelliJ.
IntelliJ handles it more advanced: if there is not other file with the same name, it just uses the file name. Otherwise it extends the displayed name with "..." and parts of the full path that make the entries unique.

So, extending the path with some unique parent folder and abbreviating common parts with "..." might be a solution.

**Comment by achimmihca** [comment]
Done.
The new implementation shows a unique folder label for files with the same name.
This is done by first finding a unique suffix for files with the same name. Afterwards these are abbreviated by finding their prefixes and skipping the rest. So you have "UNIQUE_PREFIX_OF_UNIQUE_SUFFIX / ...  FILENAME . EXTENSION".
Note that this is not minimal. However, it solves the problem and results in a unique path for files to tell them apart.

Furthermore, I added a tooltip that shows the full workspace path. This is also done in the normal editor tabs of Eclipse.
